Show how you can crash rust with a 0-length array
I'm really sorry for opening so many issues but this one seems
intellectually interesting,

It seems that a zero length position array (which can occur easily if
you try to procedurally generate points and hit an edge case)
can cause a rust panic.

I modified the example code to show how it can occur in a reproducible
way.

Backtrace included.

Not sure if there is a good way to avoid these errors at a pygfx/wgpu
level.

```
$ RUST_BACKTRACE=1 python examples/introductory/points_basic.py
Detected skylake derivative running on mesa i915. Clears to srgb textures will use manual shader clears.
thread '<unnamed>' panicked at src/conv.rs:1193:30:
invalid size
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   3: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   4: wgpuDeviceCreateBindGroup
   5: ffi_call_unix64
   6: ffi_call_int
   7: cdata_call
   8: _PyObject_Call
             at /usr/local/src/conda/python-3.12.4/Objects/call.c:367:19
   9: PyCFunction_Call
             at /usr/local/src/conda/python-3.12.4/Objects/call.c:387:12
  10: _PyEval_EvalFrameDefault
             at /home/conda/feedstock_root/build_artifacts/python-split_1718618246744/work/build-static/Python/bytecodes.c:3262:26
  11: _PyEval_EvalFrame
             at /usr/local/src/conda/python-3.12.4/Include/internal/pycore_ceval.h:89:16
  12: _PyEval_Vector
             at /usr/local/src/conda/python-3.12.4/Python/ceval.c:1683:12
  13: _PyFunction_Vectorcall
             at /usr/local/src/conda/python-3.12.4/Objects/call.c:419:16
  14: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.12.4/Include/internal/pycore_call.h:92:11
  15: method_vectorcall
             at /usr/local/src/conda/python-3.12.4/Objects/classobject.c:91:18
  16: <unknown>
  17: _ZN7QWidget5eventEP6QEvent
  18: _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent
  19: _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent
  20: _ZN14QWidgetPrivate14sendPaintEventERK7QRegion
  21: _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPoint6QFlagsINS_14DrawWidgetFlagEEP8QPainterP21QWidgetRepaintManager
  22: _ZN14QWidgetPrivate13paintOnScreenERK7QRegion
  23: _ZN13QWidgetWindow5eventEP6QEvent
  24: _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent
  25: _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent
  26: _ZN22QGuiApplicationPrivate18processExposeEventEPN29QWindowSystemInterfacePrivate11ExposeEventE
  27: _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
  28: _ZL17xcbSourceDispatchP8_GSourcePFiPvES1_
  29: g_main_dispatch
  30: g_main_context_iterate_unlocked.constprop.0
  31: g_main_context_iteration
  32: _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
  33: _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE
  34: _ZN16QCoreApplication4execEv
  35: <unknown>
  36: cfunction_vectorcall_NOARGS
             at /usr/local/src/conda/python-3.12.4/Objects/methodobject.c:481:24
  37: _PyObject_VectorcallTstate
             at /usr/local/src/conda/python-3.12.4/Include/internal/pycore_call.h:92:11
  38: PyObject_Vectorcall
             at /usr/local/src/conda/python-3.12.4/Objects/call.c:325:12
  39: _PyEval_EvalFrameDefault
             at /home/conda/feedstock_root/build_artifacts/python-split_1718618246744/work/build-static/Python/bytecodes.c:2714:19
  40: PyEval_EvalCode
             at /usr/local/src/conda/python-3.12.4/Python/ceval.c:578:21
  41: run_eval_code_obj
             at /usr/local/src/conda/python-3.12.4/Python/pythonrun.c:1722
  42: run_mod
             at /usr/local/src/conda/python-3.12.4/Python/pythonrun.c:1743
  43: pyrun_file
             at /usr/local/src/conda/python-3.12.4/Python/pythonrun.c:1643
  44: _PyRun_SimpleFileObject
             at /usr/local/src/conda/python-3.12.4/Python/pythonrun.c:433
  45: _PyRun_AnyFileObject
             at /usr/local/src/conda/python-3.12.4/Python/pythonrun.c:78
  46: pymain_run_file_obj
             at /usr/local/src/conda/python-3.12.4/Modules/main.c:360
  47: pymain_run_file
             at /usr/local/src/conda/python-3.12.4/Modules/main.c:379
  48: pymain_run_python
             at /usr/local/src/conda/python-3.12.4/Modules/main.c:629
  49: Py_RunMain
             at /usr/local/src/conda/python-3.12.4/Modules/main.c:709
  50: Py_BytesMain
             at /usr/local/src/conda/python-3.12.4/Modules/main.c:763:12
  51: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  52: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  53: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```